# ============================================
# DEV 환경
# ============================================
maru.batch.noti.email.active=true
maru.batch.noti.email.cron=0 0 5 * * ?
maru.batch.mh.meeting.reminder.active=true
maru.batch.mh.meeting.reminder.cron=0 0 9 * * ?
maru.batch.monitor.mail.cron=0 0/5 * * * ?
clients.search=dev-search-server:8080
maru.security.use-adsso-in-local=dipfox33.id
maru.upload.max-file-size-mb=100
