# ============================================
# RC 환경 (Release Candidate)
# ============================================
maru.batch.noti.email.active=true
maru.batch.noti.email.cron=0 0 7 * * ?
maru.batch.mh.meeting.reminder.active=true
maru.batch.mh.meeting.reminder.cron=0 30 9 * * ?
clients.search=rc-search-server:8080
maru.upload.max-file-size-mb=300
