-- ============================================================
-- Chipset App DB 전체 삭제 스크립트
-- 용도: 스키마 재구성 시 기존 오브젝트(테이블, 시퀀스) 전체 제거
-- 주의: FK 제약조건 순서를 지켜 삭제 (자식 → 부모)
-- ============================================================
-- ※ 구 테이블명(CHIPSET_CHIP_COL 계열)과 신 테이블명(CHIPSET_CELL_COL 계열) 모두 포함
-- ============================================================


/*
-- ===========================================================
-- [ H2 용 ]  H2 데이터베이스에서 실행 (개발 환경)
-- ===========================================================

-- ── 테이블 삭제 (자식 → 부모 순서) ──────────────────────────

-- 1) 셀 (CHIPSET_ROW, CHIPSET_CELL_COL 양쪽 모두 참조)
DROP TABLE IF EXISTS CHIPSET_CELL;
DROP TABLE IF EXISTS CHIPSET_CELL_H;

-- 2) 스펙 행
DROP TABLE IF EXISTS CHIPSET_ROW;
DROP TABLE IF EXISTS CHIPSET_ROW_H;

-- 3) 셀 컬럼 (신 명칭)
DROP TABLE IF EXISTS CHIPSET_CELL_COL;
DROP TABLE IF EXISTS CHIPSET_CELL_COL_H;

-- 4) 셀 컬럼 (구 명칭: CHIPSET_CHIP_COL → 혹시 남아 있는 경우 제거)
DROP TABLE IF EXISTS CHIPSET_CHIP_COL;
DROP TABLE IF EXISTS CHIPSET_CHIP_COL_H;

-- 5) 스펙 컬럼 메타 (신규 테이블)
DROP TABLE IF EXISTS CHIPSET_SPEC_COL;
DROP TABLE IF EXISTS CHIPSET_SPEC_COL_H;

-- 6) Raw Data
DROP TABLE IF EXISTS RAWDATA_ROW;
DROP TABLE IF EXISTS RAWDATA_ROW_H;

-- 7) 업로드 (최상위 부모)
DROP TABLE IF EXISTS CHIPSET_UPLOAD;
DROP TABLE IF EXISTS CHIPSET_UPLOAD_H;

-- ── 시퀀스 삭제 ──────────────────────────────────────────────

DROP SEQUENCE IF EXISTS SQ_CHIPSET_UPLOAD;
DROP SEQUENCE IF EXISTS SQ_CHIPSET_UPLOAD_H;

-- 셀 컬럼 (신 명칭)
DROP SEQUENCE IF EXISTS SQ_CHIPSET_CELL_COL;
DROP SEQUENCE IF EXISTS SQ_CHIPSET_CELL_COL_H;

-- 셀 컬럼 (구 명칭)
DROP SEQUENCE IF EXISTS SQ_CHIPSET_CHIP_COL;
DROP SEQUENCE IF EXISTS SQ_CHIPSET_CHIP_COL_H;

-- 스펙 컬럼 메타 (신규)
DROP SEQUENCE IF EXISTS SQ_CHIPSET_SPEC_COL;
DROP SEQUENCE IF EXISTS SQ_CHIPSET_SPEC_COL_H;

DROP SEQUENCE IF EXISTS SQ_CHIPSET_ROW;
DROP SEQUENCE IF EXISTS SQ_CHIPSET_ROW_H;
DROP SEQUENCE IF EXISTS SQ_CHIPSET_CELL;
DROP SEQUENCE IF EXISTS SQ_CHIPSET_CELL_H;
DROP SEQUENCE IF EXISTS SQ_RAWDATA_ROW;
DROP SEQUENCE IF EXISTS SQ_RAWDATA_ROW_H;
*/


-- ===========================================================
-- [ Oracle 용 ]  Oracle 19c / 21c 에서 실행 (운영 환경)
-- IF EXISTS 미지원 → PL/SQL 익명 블록으로 존재 여부 확인 후 삭제
-- 실행 방법: DBeaver 에서 블록 전체 선택 후 실행 (또는 SQL*Plus)
-- ===========================================================

-- ── 테이블 삭제 (자식 → 부모 순서) ──────────────────────────

BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_CELL      PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_CELL_H    PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_ROW       PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_ROW_H     PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
-- 신 명칭
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_CELL_COL    PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_CELL_COL_H  PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
-- 구 명칭 (남아있는 경우)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_CHIP_COL    PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_CHIP_COL_H  PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
-- 신규
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_SPEC_COL    PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_SPEC_COL_H  PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RAWDATA_ROW         PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RAWDATA_ROW_H       PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_UPLOAD      PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_UPLOAD_H    PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ── 시퀀스 삭제 ──────────────────────────────────────────────

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_UPLOAD';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_UPLOAD_H';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
-- 신 명칭
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_CELL_COL';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_CELL_COL_H';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
-- 구 명칭
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_CHIP_COL';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_CHIP_COL_H';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
-- 신규
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_SPEC_COL';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_SPEC_COL_H';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_ROW';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_ROW_H';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_CELL';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_CELL_H';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_RAWDATA_ROW';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_RAWDATA_ROW_H';        EXCEPTION WHEN OTHERS THEN NULL; END;
/

