-- ============================================================
-- Chipset App DB 전체 삭제 스크립트 (Oracle)
-- v1.2 : 2026-04-25
-- 용도: 스키마 재구성 시 기존 오브젝트 전체 제거
-- 주의: FK 제약조건 순서를 지켜 삭제 (자식 → 부모)
-- 구 테이블명(CHIPSET_ROW, RAWDATA_ROW, CHIPSET_CELL_COL 계열)도 포함
-- ============================================================
-- 실행 방법: DBeaver에서 전체 선택 후 실행 또는 SQL*Plus
-- ============================================================


-- ── 테이블 삭제 (자식 → 부모 순서) ──────────────────────────────────────────

-- 1) 셀 데이터 (CHIPSET_UPLOAD 참조)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_CELL   PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_CELL_H PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 2) RawData 컬럼 헤더 (CHIPSET_UPLOAD 참조)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_RAWDATA_COL   PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_RAWDATA_COL_H PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 3) 칩셋 컬럼 헤더 (현재 명칭)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_CHIP_COL   PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_CHIP_COL_H PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 4) 칩셋 컬럼 헤더 (구 명칭: CHIPSET_CELL_COL — v1.1에서 사용)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_CELL_COL   PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_CELL_COL_H PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 5) 스펙 컬럼 헤더
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_SPEC_COL   PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_SPEC_COL_H PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 6) 구 스펙 행 (CHIPSET_ROW — v1.1까지 사용, 현재 제거)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_ROW   PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_ROW_H PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 7) 구 RawData 행 (RAWDATA_ROW — v1.1까지 사용, 현재 제거)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RAWDATA_ROW   PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RAWDATA_ROW_H PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 8) 업로드 메타 (최상위 부모)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_UPLOAD   PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHIPSET_UPLOAD_H PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/


-- ── 시퀀스 삭제 ──────────────────────────────────────────────────────────────

-- 현재 시퀀스 (v1.2)
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_UPLOAD';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_UPLOAD_H';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_SPEC_COL';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_SPEC_COL_H';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_CHIP_COL';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_CHIP_COL_H';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_RAWDATA_COL';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_RAWDATA_COL_H';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_CELL';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_CELL_H';         EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 구 시퀀스 (v1.1 이전 — 혹시 남아있는 경우 제거)
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_CELL_COL';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_CELL_COL_H';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_CHIP_COL_OLD';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_ROW';            EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_CHIPSET_ROW_H';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_RAWDATA_ROW';            EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SQ_RAWDATA_ROW_H';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
